/*******************************************************************************
 * Copyright (c) 2006-2010 eBay Inc. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *******************************************************************************/
package org.ebayopensource.turmeric.tools.codegen;

import javax.wsdl.WSDLException;

import org.ebayopensource.turmeric.tools.codegen.exception.CodeGenFailedException;


/**
 * Contract interface class that every code generator must implement.
 * 
 * 
 * @author rmandapati
 */
public interface SourceGenerator {

	public void generate(CodeGenContext codeGenCtx) throws CodeGenFailedException, WSDLException;
	
	public boolean continueOnError();
	
	/**
	 * returns the relative filePath for the Artifact generated by their respective Generators.
	 * @param serviceAdminName Name of the Service
	 * @param interfaceName name of the Interface corresponding to the Service
	 * @return The relative path of the Artifact
	 * @author arajmony
	 */
	
	public String getFilePath(String serviceAdminName, String interfaceName);
}
