/*******************************************************************************
 * Copyright (c) 2006-2010 eBay Inc. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.18 at 03:20:10 AM PDT 
//


package org.ebayopensource.turmeric.services.repository.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ebayopensource.turmeric.services.repository.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RepositoryServiceProviderConfig_QNAME = new QName("http://www.ebayopensource.org/turmeric/services/repository/config", "repository-service-provider-config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ebayopensource.turmeric.services.repository.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RepositoryServiceProviderConfig }
     * 
     */
    public RepositoryServiceProviderConfig createRepositoryServiceProviderConfig() {
        return new RepositoryServiceProviderConfig();
    }

    /**
     * Create an instance of {@link RepositoryServiceProviderList }
     * 
     */
    public RepositoryServiceProviderList createRepositoryServiceProviderList() {
        return new RepositoryServiceProviderList();
    }

    /**
     * Create an instance of {@link RepositoryServiceProviders }
     * 
     */
    public RepositoryServiceProviders createRepositoryServiceProviders() {
        return new RepositoryServiceProviders();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RepositoryServiceProviderConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebayopensource.org/turmeric/services/repository/config", name = "repository-service-provider-config")
    public JAXBElement<RepositoryServiceProviderConfig> createRepositoryServiceProviderConfig(RepositoryServiceProviderConfig value) {
        return new JAXBElement<RepositoryServiceProviderConfig>(_RepositoryServiceProviderConfig_QNAME, RepositoryServiceProviderConfig.class, null, value);
    }

}
