/*******************************************************************************
 * Copyright (c) 2006-2010 eBay Inc. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.18 at 03:20:10 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ebayopensource.org/turmeric/services/repository/config", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.ebayopensource.turmeric.services.repository.config;
