//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 						This is the abstract type of distribution
 * 						response.
 * 					
 * 
 * <p>Java class for AbstractDistributionResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractDistributionResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="simpleCountDistributionResponse" type="{http://www.ebay.com/marketplace/search/v1/services}SimpleCountDistributionResponse"/>
 *         &lt;element name="distributionResponse" type="{http://www.ebay.com/marketplace/search/v1/services}DistributionResponse"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractDistributionResponse", propOrder = {
    "simpleCountDistributionResponse",
    "distributionResponse"
})
public class AbstractDistributionResponse {

    protected SimpleCountDistributionResponse simpleCountDistributionResponse;
    protected DistributionResponse distributionResponse;

    /**
     * Gets the value of the simpleCountDistributionResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleCountDistributionResponse }
     *     
     */
    public SimpleCountDistributionResponse getSimpleCountDistributionResponse() {
        return simpleCountDistributionResponse;
    }

    /**
     * Sets the value of the simpleCountDistributionResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleCountDistributionResponse }
     *     
     */
    public void setSimpleCountDistributionResponse(SimpleCountDistributionResponse value) {
        this.simpleCountDistributionResponse = value;
    }

    /**
     * Gets the value of the distributionResponse property.
     * 
     * @return
     *     possible object is
     *     {@link DistributionResponse }
     *     
     */
    public DistributionResponse getDistributionResponse() {
        return distributionResponse;
    }

    /**
     * Sets the value of the distributionResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionResponse }
     *     
     */
    public void setDistributionResponse(DistributionResponse value) {
        this.distributionResponse = value;
    }

}
