//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 						This is the abstract type of distribution
 * 						request.
 * 					
 * 
 * <p>Java class for AbstractDistributionRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractDistributionRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="simpleCountDistributionRequest" type="{http://www.ebay.com/marketplace/search/v1/services}SimpleCountDistributionRequest"/>
 *         &lt;element name="distributionRequest" type="{http://www.ebay.com/marketplace/search/v1/services}DistributionRequest"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractDistributionRequest", propOrder = {
    "simpleCountDistributionRequest",
    "distributionRequest"
})
public class AbstractDistributionRequest {

    protected SimpleCountDistributionRequest simpleCountDistributionRequest;
    protected DistributionRequest distributionRequest;

    /**
     * Gets the value of the simpleCountDistributionRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleCountDistributionRequest }
     *     
     */
    public SimpleCountDistributionRequest getSimpleCountDistributionRequest() {
        return simpleCountDistributionRequest;
    }

    /**
     * Sets the value of the simpleCountDistributionRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleCountDistributionRequest }
     *     
     */
    public void setSimpleCountDistributionRequest(SimpleCountDistributionRequest value) {
        this.simpleCountDistributionRequest = value;
    }

    /**
     * Gets the value of the distributionRequest property.
     * 
     * @return
     *     possible object is
     *     {@link DistributionRequest }
     *     
     */
    public DistributionRequest getDistributionRequest() {
        return distributionRequest;
    }

    /**
     * Sets the value of the distributionRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionRequest }
     *     
     */
    public void setDistributionRequest(DistributionRequest value) {
        this.distributionRequest = value;
    }

}
