//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AggregateNumericOperator.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AggregateNumericOperator">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MIN"/>
 *     &lt;enumeration value="MAX"/>
 *     &lt;enumeration value="SUM"/>
 *     &lt;enumeration value="COUNT"/>
 *     &lt;enumeration value="UNIQUE"/>
 *     &lt;enumeration value="PROJECT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AggregateNumericOperator")
@XmlEnum
public enum AggregateNumericOperator {


    /**
     * 
     * 								Corresponding to the min() aggregate
     * 								function
     * 								defined in Search Backend.
     * 							
     * 
     */
    MIN,

    /**
     * 
     * 								Corresponding to the max() aggregate
     * 								function
     * 								defined in Search Backend
     * 							
     * 
     */
    MAX,

    /**
     * 
     * 								Corresponding to the sum() aggregate
     * 								function
     * 								defined in Search Backend
     * 							
     * 
     */
    SUM,

    /**
     * 
     * 								Corresponding to the count() aggregate
     * 								function
     * 								defined in Search Backend
     * 							
     * 
     */
    COUNT,

    /**
     * 
     * 								Corresponding to the unique() aggregate
     * 								function defined in Search Backend
     * 							
     * 
     */
    UNIQUE,

    /**
     * 
     * 								Corresponding to the project() aggregate
     * 								function defined in Search Backend
     * 							
     * 
     */
    PROJECT;

    public String value() {
        return name();
    }

    public static AggregateNumericOperator fromValue(String v) {
        return valueOf(v);
    }

}
