//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseImageSimilaritySortType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseImageSimilaritySortType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="imageSimilaritySortTypeByItem" type="{http://www.ebay.com/marketplace/search/v1/services}ImageSimilaritySortTypeByItem"/>
 *         &lt;element name="imageSimilaritySortTypeBySignature" type="{http://www.ebay.com/marketplace/search/v1/services}ImageSimilaritySortTypeBySignature"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseImageSimilaritySortType", propOrder = {
    "imageSimilaritySortTypeByItem",
    "imageSimilaritySortTypeBySignature"
})
public class BaseImageSimilaritySortType {

    protected ImageSimilaritySortTypeByItem imageSimilaritySortTypeByItem;
    protected ImageSimilaritySortTypeBySignature imageSimilaritySortTypeBySignature;

    /**
     * Gets the value of the imageSimilaritySortTypeByItem property.
     * 
     * @return
     *     possible object is
     *     {@link ImageSimilaritySortTypeByItem }
     *     
     */
    public ImageSimilaritySortTypeByItem getImageSimilaritySortTypeByItem() {
        return imageSimilaritySortTypeByItem;
    }

    /**
     * Sets the value of the imageSimilaritySortTypeByItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageSimilaritySortTypeByItem }
     *     
     */
    public void setImageSimilaritySortTypeByItem(ImageSimilaritySortTypeByItem value) {
        this.imageSimilaritySortTypeByItem = value;
    }

    /**
     * Gets the value of the imageSimilaritySortTypeBySignature property.
     * 
     * @return
     *     possible object is
     *     {@link ImageSimilaritySortTypeBySignature }
     *     
     */
    public ImageSimilaritySortTypeBySignature getImageSimilaritySortTypeBySignature() {
        return imageSimilaritySortTypeBySignature;
    }

    /**
     * Sets the value of the imageSimilaritySortTypeBySignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageSimilaritySortTypeBySignature }
     *     
     */
    public void setImageSimilaritySortTypeBySignature(ImageSimilaritySortTypeBySignature value) {
        this.imageSimilaritySortTypeBySignature = value;
    }

}
