//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 						This type defines the voyager constraint.
 * 					
 * 
 * <p>Java class for Constraint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Constraint">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="internalExpression" type="{http://www.ebay.com/marketplace/search/v1/services}LogicalExpression"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Constraint", propOrder = {
    "internalExpression"
})
public class Constraint {

    @XmlElement(required = true)
    protected LogicalExpression internalExpression;

    /**
     * Gets the value of the internalExpression property.
     * 
     * @return
     *     possible object is
     *     {@link LogicalExpression }
     *     
     */
    public LogicalExpression getInternalExpression() {
        return internalExpression;
    }

    /**
     * Sets the value of the internalExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicalExpression }
     *     
     */
    public void setInternalExpression(LogicalExpression value) {
        this.internalExpression = value;
    }

}
