//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DistributionSortType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DistributionSortType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ByField"/>
 *     &lt;enumeration value="ByValue"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DistributionSortType")
@XmlEnum
public enum DistributionSortType {


    /**
     * 
     * 								This is the type to choose if the
     * 								distribution
     * 								needs to be sorted on the
     * 								values of the field as in the
     * 								Distribution Request.
     * 							
     * 
     */
    @XmlEnumValue("ByField")
    BY_FIELD("ByField"),

    /**
     * 
     * 								This is the type to choose if the
     * 								distribution
     * 								needs to be sorted on the
     * 								values as in the Distribution Response.
     * 							
     * 
     */
    @XmlEnumValue("ByValue")
    BY_VALUE("ByValue");
    private final String value;

    DistributionSortType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DistributionSortType fromValue(String v) {
        for (DistributionSortType c: DistributionSortType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
