//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 						DistributionSortBy is used to define the order
 * 						of
 * 						distribution result entries.
 * 					
 * 
 * <p>Java class for DistributionSortBy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DistributionSortBy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sortStrategy" type="{http://www.ebay.com/marketplace/search/v1/services}DistributionSortStrategy" minOccurs="0"/>
 *         &lt;element name="sortType" type="{http://www.ebay.com/marketplace/search/v1/services}DistributionSortType" minOccurs="0"/>
 *         &lt;element name="sortOrder" type="{http://www.ebay.com/marketplace/search/v1/services}SortOrder" minOccurs="0"/>
 *         &lt;element name="sortbyvalue" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DistributionSortBy", propOrder = {
    "sortStrategy",
    "sortType",
    "sortOrder",
    "sortbyvalue"
})
public class DistributionSortBy {

    protected DistributionSortStrategy sortStrategy;
    protected DistributionSortType sortType;
    protected SortOrder sortOrder;
    protected Boolean sortbyvalue;

    /**
     * Gets the value of the sortStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link DistributionSortStrategy }
     *     
     */
    public DistributionSortStrategy getSortStrategy() {
        return sortStrategy;
    }

    /**
     * Sets the value of the sortStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionSortStrategy }
     *     
     */
    public void setSortStrategy(DistributionSortStrategy value) {
        this.sortStrategy = value;
    }

    /**
     * Gets the value of the sortType property.
     * 
     * @return
     *     possible object is
     *     {@link DistributionSortType }
     *     
     */
    public DistributionSortType getSortType() {
        return sortType;
    }

    /**
     * Sets the value of the sortType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionSortType }
     *     
     */
    public void setSortType(DistributionSortType value) {
        this.sortType = value;
    }

    /**
     * Gets the value of the sortOrder property.
     * 
     * @return
     *     possible object is
     *     {@link SortOrder }
     *     
     */
    public SortOrder getSortOrder() {
        return sortOrder;
    }

    /**
     * Sets the value of the sortOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link SortOrder }
     *     
     */
    public void setSortOrder(SortOrder value) {
        this.sortOrder = value;
    }

    /**
     * Gets the value of the sortbyvalue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSortbyvalue() {
        return sortbyvalue;
    }

    /**
     * Sets the value of the sortbyvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSortbyvalue(Boolean value) {
        this.sortbyvalue = value;
    }

}
