//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 						This type defines the distribution field.
 * 						includeOtherValues is valid if the distribution
 * 						of this field is
 * 						range or enumeration and
 * 						includes "others"
 * 					
 * 
 * <p>Java class for DistributionField complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DistributionField">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="field" type="{http://www.ebay.com/marketplace/search/v1/services}Field"/>
 *         &lt;choice>
 *           &lt;element name="range" type="{http://www.ebay.com/marketplace/search/v1/services}RangeValue" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="enumeration" type="{http://www.ebay.com/marketplace/search/v1/services}EnumerationValue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="includeOtherValues" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DistributionField", propOrder = {
    "field",
    "range",
    "enumeration",
    "includeOtherValues"
})
public class DistributionField {

    @XmlElement(required = true)
    protected Field field;
    protected List<RangeValue> range;
    protected List<EnumerationValue> enumeration;
    protected Boolean includeOtherValues;

    /**
     * Gets the value of the field property.
     * 
     * @return
     *     possible object is
     *     {@link Field }
     *     
     */
    public Field getField() {
        return field;
    }

    /**
     * Sets the value of the field property.
     * 
     * @param value
     *     allowed object is
     *     {@link Field }
     *     
     */
    public void setField(Field value) {
        this.field = value;
    }

    /**
     * Gets the value of the range property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the range property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RangeValue }
     * 
     * 
     */
    public List<RangeValue> getRange() {
        if (range == null) {
            range = new ArrayList<RangeValue>();
        }
        return this.range;
    }

    /**
     * Gets the value of the enumeration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enumeration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnumeration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnumerationValue }
     * 
     * 
     */
    public List<EnumerationValue> getEnumeration() {
        if (enumeration == null) {
            enumeration = new ArrayList<EnumerationValue>();
        }
        return this.enumeration;
    }

    /**
     * Gets the value of the includeOtherValues property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeOtherValues() {
        return includeOtherValues;
    }

    /**
     * Sets the value of the includeOtherValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeOtherValues(Boolean value) {
        this.includeOtherValues = value;
    }

}
