//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 						This type defines distribution request.
 * 					
 * 
 * <p>Java class for DistributionRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DistributionRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ebay.com/marketplace/search/v1/services}AbstractDistributionRequestBase">
 *       &lt;sequence>
 *         &lt;element name="distributionFields" type="{http://www.ebay.com/marketplace/search/v1/services}DistributionField" maxOccurs="unbounded"/>
 *         &lt;element name="aggregateFunction" type="{http://www.ebay.com/marketplace/search/v1/services}AggregateNumericExpression" maxOccurs="unbounded"/>
 *         &lt;element name="distributionSort" type="{http://www.ebay.com/marketplace/search/v1/services}DistributionSortBy"/>
 *         &lt;element name="requestHeader" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DistributionRequest", propOrder = {
    "distributionFields",
    "aggregateFunction",
    "distributionSort",
    "requestHeader"
})
public class DistributionRequest
    extends AbstractDistributionRequestBase
{

    @XmlElement(required = true)
    protected List<DistributionField> distributionFields;
    @XmlElement(required = true)
    protected List<AggregateNumericExpression> aggregateFunction;
    @XmlElement(required = true)
    protected DistributionSortBy distributionSort;
    protected Boolean requestHeader;

    /**
     * Gets the value of the distributionFields property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the distributionFields property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDistributionFields().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DistributionField }
     * 
     * 
     */
    public List<DistributionField> getDistributionFields() {
        if (distributionFields == null) {
            distributionFields = new ArrayList<DistributionField>();
        }
        return this.distributionFields;
    }

    /**
     * Gets the value of the aggregateFunction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aggregateFunction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAggregateFunction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AggregateNumericExpression }
     * 
     * 
     */
    public List<AggregateNumericExpression> getAggregateFunction() {
        if (aggregateFunction == null) {
            aggregateFunction = new ArrayList<AggregateNumericExpression>();
        }
        return this.aggregateFunction;
    }

    /**
     * Gets the value of the distributionSort property.
     * 
     * @return
     *     possible object is
     *     {@link DistributionSortBy }
     *     
     */
    public DistributionSortBy getDistributionSort() {
        return distributionSort;
    }

    /**
     * Sets the value of the distributionSort property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionSortBy }
     *     
     */
    public void setDistributionSort(DistributionSortBy value) {
        this.distributionSort = value;
    }

    /**
     * Gets the value of the requestHeader property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequestHeader() {
        return requestHeader;
    }

    /**
     * Sets the value of the requestHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequestHeader(Boolean value) {
        this.requestHeader = value;
    }

}
