//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 						This is the abstract type for field value.
 * 					
 * 
 * <p>Java class for FieldValue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FieldValue">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="shippingCostFieldValue" type="{http://www.ebay.com/marketplace/search/v1/services}ShippingCostFieldValue"/>
 *         &lt;element name="traitFieldValue" type="{http://www.ebay.com/marketplace/search/v1/services}TraitFieldValue"/>
 *         &lt;element name="sellerLogoFieldValue" type="{http://www.ebay.com/marketplace/search/v1/services}SellerLogoFieldValue"/>
 *         &lt;element name="booleanFieldValue" type="{http://www.ebay.com/marketplace/search/v1/services}BooleanFieldValue"/>
 *         &lt;element name="dateFieldValue" type="{http://www.ebay.com/marketplace/search/v1/services}DateFieldValue"/>
 *         &lt;element name="doubleFieldValue" type="{http://www.ebay.com/marketplace/search/v1/services}DoubleFieldValue"/>
 *         &lt;element name="longFieldValue" type="{http://www.ebay.com/marketplace/search/v1/services}LongFieldValue"/>
 *         &lt;element name="moneyFieldValue" type="{http://www.ebay.com/marketplace/search/v1/services}MoneyFieldValue"/>
 *         &lt;element name="stringFieldValue" type="{http://www.ebay.com/marketplace/search/v1/services}StringFieldValue"/>
 *         &lt;element name="fitmentFieldValue" type="{http://www.ebay.com/marketplace/search/v1/services}FitmentFieldValue"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FieldValue", propOrder = {
    "shippingCostFieldValue",
    "traitFieldValue",
    "sellerLogoFieldValue",
    "booleanFieldValue",
    "dateFieldValue",
    "doubleFieldValue",
    "longFieldValue",
    "moneyFieldValue",
    "stringFieldValue",
    "fitmentFieldValue"
})
public class FieldValue {

    protected ShippingCostFieldValue shippingCostFieldValue;
    protected TraitFieldValue traitFieldValue;
    protected SellerLogoFieldValue sellerLogoFieldValue;
    protected BooleanFieldValue booleanFieldValue;
    protected DateFieldValue dateFieldValue;
    protected DoubleFieldValue doubleFieldValue;
    protected LongFieldValue longFieldValue;
    protected MoneyFieldValue moneyFieldValue;
    protected StringFieldValue stringFieldValue;
    protected FitmentFieldValue fitmentFieldValue;

    /**
     * Gets the value of the shippingCostFieldValue property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingCostFieldValue }
     *     
     */
    public ShippingCostFieldValue getShippingCostFieldValue() {
        return shippingCostFieldValue;
    }

    /**
     * Sets the value of the shippingCostFieldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingCostFieldValue }
     *     
     */
    public void setShippingCostFieldValue(ShippingCostFieldValue value) {
        this.shippingCostFieldValue = value;
    }

    /**
     * Gets the value of the traitFieldValue property.
     * 
     * @return
     *     possible object is
     *     {@link TraitFieldValue }
     *     
     */
    public TraitFieldValue getTraitFieldValue() {
        return traitFieldValue;
    }

    /**
     * Sets the value of the traitFieldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link TraitFieldValue }
     *     
     */
    public void setTraitFieldValue(TraitFieldValue value) {
        this.traitFieldValue = value;
    }

    /**
     * Gets the value of the sellerLogoFieldValue property.
     * 
     * @return
     *     possible object is
     *     {@link SellerLogoFieldValue }
     *     
     */
    public SellerLogoFieldValue getSellerLogoFieldValue() {
        return sellerLogoFieldValue;
    }

    /**
     * Sets the value of the sellerLogoFieldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link SellerLogoFieldValue }
     *     
     */
    public void setSellerLogoFieldValue(SellerLogoFieldValue value) {
        this.sellerLogoFieldValue = value;
    }

    /**
     * Gets the value of the booleanFieldValue property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanFieldValue }
     *     
     */
    public BooleanFieldValue getBooleanFieldValue() {
        return booleanFieldValue;
    }

    /**
     * Sets the value of the booleanFieldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanFieldValue }
     *     
     */
    public void setBooleanFieldValue(BooleanFieldValue value) {
        this.booleanFieldValue = value;
    }

    /**
     * Gets the value of the dateFieldValue property.
     * 
     * @return
     *     possible object is
     *     {@link DateFieldValue }
     *     
     */
    public DateFieldValue getDateFieldValue() {
        return dateFieldValue;
    }

    /**
     * Sets the value of the dateFieldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFieldValue }
     *     
     */
    public void setDateFieldValue(DateFieldValue value) {
        this.dateFieldValue = value;
    }

    /**
     * Gets the value of the doubleFieldValue property.
     * 
     * @return
     *     possible object is
     *     {@link DoubleFieldValue }
     *     
     */
    public DoubleFieldValue getDoubleFieldValue() {
        return doubleFieldValue;
    }

    /**
     * Sets the value of the doubleFieldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoubleFieldValue }
     *     
     */
    public void setDoubleFieldValue(DoubleFieldValue value) {
        this.doubleFieldValue = value;
    }

    /**
     * Gets the value of the longFieldValue property.
     * 
     * @return
     *     possible object is
     *     {@link LongFieldValue }
     *     
     */
    public LongFieldValue getLongFieldValue() {
        return longFieldValue;
    }

    /**
     * Sets the value of the longFieldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link LongFieldValue }
     *     
     */
    public void setLongFieldValue(LongFieldValue value) {
        this.longFieldValue = value;
    }

    /**
     * Gets the value of the moneyFieldValue property.
     * 
     * @return
     *     possible object is
     *     {@link MoneyFieldValue }
     *     
     */
    public MoneyFieldValue getMoneyFieldValue() {
        return moneyFieldValue;
    }

    /**
     * Sets the value of the moneyFieldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoneyFieldValue }
     *     
     */
    public void setMoneyFieldValue(MoneyFieldValue value) {
        this.moneyFieldValue = value;
    }

    /**
     * Gets the value of the stringFieldValue property.
     * 
     * @return
     *     possible object is
     *     {@link StringFieldValue }
     *     
     */
    public StringFieldValue getStringFieldValue() {
        return stringFieldValue;
    }

    /**
     * Sets the value of the stringFieldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringFieldValue }
     *     
     */
    public void setStringFieldValue(StringFieldValue value) {
        this.stringFieldValue = value;
    }

    /**
     * Gets the value of the fitmentFieldValue property.
     * 
     * @return
     *     possible object is
     *     {@link FitmentFieldValue }
     *     
     */
    public FitmentFieldValue getFitmentFieldValue() {
        return fitmentFieldValue;
    }

    /**
     * Sets the value of the fitmentFieldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link FitmentFieldValue }
     *     
     */
    public void setFitmentFieldValue(FitmentFieldValue value) {
        this.fitmentFieldValue = value;
    }

}
