//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for FindItemsByIdsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FindItemsByIdsResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ebay.com/marketplace/search/v1/services}BaseServiceResponse">
 *       &lt;sequence>
 *         &lt;element name="matchCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="itemResults" type="{http://www.ebay.com/marketplace/search/v1/services}SearchRecord" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="diagnosticInfo" type="{http://www.ebay.com/marketplace/search/v1/services}DiagnosticInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="executionTime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FindItemsByIdsResponse", propOrder = {
    "matchCount",
    "itemResults",
    "diagnosticInfo",
    "executionTime"
})
public class FindItemsByIdsResponse
    extends BaseServiceResponse
{

    protected int matchCount;
    protected List<SearchRecord> itemResults;
    protected List<DiagnosticInfo> diagnosticInfo;
    protected long executionTime;

    /**
     * Gets the value of the matchCount property.
     * 
     */
    public int getMatchCount() {
        return matchCount;
    }

    /**
     * Sets the value of the matchCount property.
     * 
     */
    public void setMatchCount(int value) {
        this.matchCount = value;
    }

    /**
     * Gets the value of the itemResults property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemResults property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemResults().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SearchRecord }
     * 
     * 
     */
    public List<SearchRecord> getItemResults() {
        if (itemResults == null) {
            itemResults = new ArrayList<SearchRecord>();
        }
        return this.itemResults;
    }

    /**
     * Gets the value of the diagnosticInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diagnosticInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiagnosticInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DiagnosticInfo }
     * 
     * 
     */
    public List<DiagnosticInfo> getDiagnosticInfo() {
        if (diagnosticInfo == null) {
            diagnosticInfo = new ArrayList<DiagnosticInfo>();
        }
        return this.diagnosticInfo;
    }

    /**
     * Gets the value of the executionTime property.
     * 
     */
    public long getExecutionTime() {
        return executionTime;
    }

    /**
     * Sets the value of the executionTime property.
     * 
     */
    public void setExecutionTime(long value) {
        this.executionTime = value;
    }

}
