//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for FindItemsByIdsRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FindItemsByIdsRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ebay.com/marketplace/search/v1/services}BaseServiceRequest">
 *       &lt;sequence>
 *         &lt;element name="serviceContext" type="{http://www.ebay.com/marketplace/search/v1/services}ServiceContext"/>
 *         &lt;element name="itemSearchScope" type="{http://www.ebay.com/marketplace/search/v1/services}ItemSearchScopeEnum" minOccurs="0"/>
 *         &lt;element name="readSet" type="{http://www.ebay.com/marketplace/search/v1/services}Field" maxOccurs="unbounded"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded"/>
 *         &lt;element name="includeDiagnosticInfo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FindItemsByIdsRequest", propOrder = {
    "serviceContext",
    "itemSearchScope",
    "readSet",
    "id",
    "includeDiagnosticInfo"
})
public class FindItemsByIdsRequest
    extends BaseServiceRequest
{

    @XmlElement(required = true)
    protected ServiceContext serviceContext;
    protected ItemSearchScopeEnum itemSearchScope;
    @XmlElement(required = true)
    protected List<Field> readSet;
    @XmlElement(type = Long.class)
    protected List<Long> id;
    protected Boolean includeDiagnosticInfo;

    /**
     * Gets the value of the serviceContext property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceContext }
     *     
     */
    public ServiceContext getServiceContext() {
        return serviceContext;
    }

    /**
     * Sets the value of the serviceContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceContext }
     *     
     */
    public void setServiceContext(ServiceContext value) {
        this.serviceContext = value;
    }

    /**
     * Gets the value of the itemSearchScope property.
     * 
     * @return
     *     possible object is
     *     {@link ItemSearchScopeEnum }
     *     
     */
    public ItemSearchScopeEnum getItemSearchScope() {
        return itemSearchScope;
    }

    /**
     * Sets the value of the itemSearchScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemSearchScopeEnum }
     *     
     */
    public void setItemSearchScope(ItemSearchScopeEnum value) {
        this.itemSearchScope = value;
    }

    /**
     * Gets the value of the readSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the readSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReadSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * 
     * 
     */
    public List<Field> getReadSet() {
        if (readSet == null) {
            readSet = new ArrayList<Field>();
        }
        return this.readSet;
    }

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getId() {
        if (id == null) {
            id = new ArrayList<Long>();
        }
        return this.id;
    }

    /**
     * Gets the value of the includeDiagnosticInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeDiagnosticInfo() {
        return includeDiagnosticInfo;
    }

    /**
     * Sets the value of the includeDiagnosticInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeDiagnosticInfo(Boolean value) {
        this.includeDiagnosticInfo = value;
    }

}
