//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 						FindItemsResponse is used to define the response
 * 						for findItems operation.
 * 					
 * 
 * <p>Java class for FindItemsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FindItemsResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ebay.com/marketplace/search/v1/services}BaseServiceResponse">
 *       &lt;sequence>
 *         &lt;element name="resultSummaryInfo" type="{http://www.ebay.com/marketplace/search/v1/services}ResultSummaryInfo" minOccurs="0"/>
 *         &lt;element name="searchResultSet" type="{http://www.ebay.com/marketplace/search/v1/services}SearchRecord" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="distributionResultSet" type="{http://www.ebay.com/marketplace/search/v1/services}AbstractDistributionResponse" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="bucketResultSet" type="{http://www.ebay.com/marketplace/search/v1/services}BucketResponse" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="permutationResult" type="{http://www.ebay.com/marketplace/search/v1/services}PermutationResponse" minOccurs="0"/>
 *         &lt;element name="fitmentResult" type="{http://www.ebay.com/marketplace/search/v1/services}FitmentResponse" minOccurs="0"/>
 *         &lt;element name="diagnosticInfo" type="{http://www.ebay.com/marketplace/search/v1/services}DiagnosticInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="executionTime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="dfnResponse" type="{http://www.ebay.com/marketplace/search/v1/services}DominantProductTypeResponse" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FindItemsResponse", propOrder = {
    "resultSummaryInfo",
    "searchResultSet",
    "distributionResultSet",
    "bucketResultSet",
    "permutationResult",
    "fitmentResult",
    "diagnosticInfo",
    "executionTime",
    "dfnResponse"
})
public class FindItemsResponse
    extends BaseServiceResponse
{

    protected ResultSummaryInfo resultSummaryInfo;
    protected List<SearchRecord> searchResultSet;
    protected List<AbstractDistributionResponse> distributionResultSet;
    protected List<BucketResponse> bucketResultSet;
    protected PermutationResponse permutationResult;
    protected FitmentResponse fitmentResult;
    protected List<DiagnosticInfo> diagnosticInfo;
    protected long executionTime;
    protected DominantProductTypeResponse dfnResponse;

    /**
     * Gets the value of the resultSummaryInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ResultSummaryInfo }
     *     
     */
    public ResultSummaryInfo getResultSummaryInfo() {
        return resultSummaryInfo;
    }

    /**
     * Sets the value of the resultSummaryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultSummaryInfo }
     *     
     */
    public void setResultSummaryInfo(ResultSummaryInfo value) {
        this.resultSummaryInfo = value;
    }

    /**
     * Gets the value of the searchResultSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the searchResultSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSearchResultSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SearchRecord }
     * 
     * 
     */
    public List<SearchRecord> getSearchResultSet() {
        if (searchResultSet == null) {
            searchResultSet = new ArrayList<SearchRecord>();
        }
        return this.searchResultSet;
    }

    /**
     * Gets the value of the distributionResultSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the distributionResultSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDistributionResultSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbstractDistributionResponse }
     * 
     * 
     */
    public List<AbstractDistributionResponse> getDistributionResultSet() {
        if (distributionResultSet == null) {
            distributionResultSet = new ArrayList<AbstractDistributionResponse>();
        }
        return this.distributionResultSet;
    }

    /**
     * Gets the value of the bucketResultSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bucketResultSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBucketResultSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BucketResponse }
     * 
     * 
     */
    public List<BucketResponse> getBucketResultSet() {
        if (bucketResultSet == null) {
            bucketResultSet = new ArrayList<BucketResponse>();
        }
        return this.bucketResultSet;
    }

    /**
     * Gets the value of the permutationResult property.
     * 
     * @return
     *     possible object is
     *     {@link PermutationResponse }
     *     
     */
    public PermutationResponse getPermutationResult() {
        return permutationResult;
    }

    /**
     * Sets the value of the permutationResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermutationResponse }
     *     
     */
    public void setPermutationResult(PermutationResponse value) {
        this.permutationResult = value;
    }

    /**
     * Gets the value of the fitmentResult property.
     * 
     * @return
     *     possible object is
     *     {@link FitmentResponse }
     *     
     */
    public FitmentResponse getFitmentResult() {
        return fitmentResult;
    }

    /**
     * Sets the value of the fitmentResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link FitmentResponse }
     *     
     */
    public void setFitmentResult(FitmentResponse value) {
        this.fitmentResult = value;
    }

    /**
     * Gets the value of the diagnosticInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diagnosticInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiagnosticInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DiagnosticInfo }
     * 
     * 
     */
    public List<DiagnosticInfo> getDiagnosticInfo() {
        if (diagnosticInfo == null) {
            diagnosticInfo = new ArrayList<DiagnosticInfo>();
        }
        return this.diagnosticInfo;
    }

    /**
     * Gets the value of the executionTime property.
     * 
     */
    public long getExecutionTime() {
        return executionTime;
    }

    /**
     * Sets the value of the executionTime property.
     * 
     */
    public void setExecutionTime(long value) {
        this.executionTime = value;
    }

    /**
     * Gets the value of the dfnResponse property.
     * 
     * @return
     *     possible object is
     *     {@link DominantProductTypeResponse }
     *     
     */
    public DominantProductTypeResponse getDfnResponse() {
        return dfnResponse;
    }

    /**
     * Sets the value of the dfnResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link DominantProductTypeResponse }
     *     
     */
    public void setDfnResponse(DominantProductTypeResponse value) {
        this.dfnResponse = value;
    }

}
