//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 						Searches for items based on given constraints
 * 						and
 * 						returns details for matching items according
 * 						to required fields.
 * 					
 * 
 * <p>Java class for FindItemsRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FindItemsRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ebay.com/marketplace/search/v1/services}BaseServiceRequest">
 *       &lt;sequence>
 *         &lt;element name="serviceContext" type="{http://www.ebay.com/marketplace/search/v1/services}ServiceContext"/>
 *         &lt;element name="itemSearchScope" type="{http://www.ebay.com/marketplace/search/v1/services}ItemSearchScopeEnum"/>
 *         &lt;element name="fetchOffset" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="fetchSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="readSet" type="{http://www.ebay.com/marketplace/search/v1/services}Field" maxOccurs="unbounded"/>
 *         &lt;element name="constraint" type="{http://www.ebay.com/marketplace/search/v1/services}Constraint" maxOccurs="unbounded"/>
 *         &lt;element name="sortBy" type="{http://www.ebay.com/marketplace/search/v1/services}SortBy" maxOccurs="4"/>
 *         &lt;element name="distribution" type="{http://www.ebay.com/marketplace/search/v1/services}AbstractDistributionRequest" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="bucket" type="{http://www.ebay.com/marketplace/search/v1/services}BucketRequest" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="permutation" type="{http://www.ebay.com/marketplace/search/v1/services}PermutationRequest" minOccurs="0"/>
 *         &lt;element name="uniqueBy" type="{http://www.ebay.com/marketplace/search/v1/services}UniqueBy" minOccurs="0"/>
 *         &lt;element name="blendBy" type="{http://www.ebay.com/marketplace/search/v1/services}BlendBy" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="includeDiagnosticInfo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="dfn" type="{http://www.ebay.com/marketplace/search/v1/services}DominantProductTypeRequest" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FindItemsRequest", propOrder = {
    "serviceContext",
    "itemSearchScope",
    "fetchOffset",
    "fetchSize",
    "readSet",
    "constraint",
    "sortBy",
    "distribution",
    "bucket",
    "permutation",
    "uniqueBy",
    "blendBy",
    "includeDiagnosticInfo",
    "dfn"
})
public class FindItemsRequest
    extends BaseServiceRequest
{

    @XmlElement(required = true)
    protected ServiceContext serviceContext;
    @XmlElement(required = true)
    protected ItemSearchScopeEnum itemSearchScope;
    protected int fetchOffset;
    protected int fetchSize;
    @XmlElement(required = true)
    protected List<Field> readSet;
    @XmlElement(required = true)
    protected List<Constraint> constraint;
    @XmlElement(required = true)
    protected List<SortBy> sortBy;
    protected List<AbstractDistributionRequest> distribution;
    protected List<BucketRequest> bucket;
    protected PermutationRequest permutation;
    protected UniqueBy uniqueBy;
    protected List<BlendBy> blendBy;
    protected Boolean includeDiagnosticInfo;
    protected DominantProductTypeRequest dfn;

    /**
     * Gets the value of the serviceContext property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceContext }
     *     
     */
    public ServiceContext getServiceContext() {
        return serviceContext;
    }

    /**
     * Sets the value of the serviceContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceContext }
     *     
     */
    public void setServiceContext(ServiceContext value) {
        this.serviceContext = value;
    }

    /**
     * Gets the value of the itemSearchScope property.
     * 
     * @return
     *     possible object is
     *     {@link ItemSearchScopeEnum }
     *     
     */
    public ItemSearchScopeEnum getItemSearchScope() {
        return itemSearchScope;
    }

    /**
     * Sets the value of the itemSearchScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemSearchScopeEnum }
     *     
     */
    public void setItemSearchScope(ItemSearchScopeEnum value) {
        this.itemSearchScope = value;
    }

    /**
     * Gets the value of the fetchOffset property.
     * 
     */
    public int getFetchOffset() {
        return fetchOffset;
    }

    /**
     * Sets the value of the fetchOffset property.
     * 
     */
    public void setFetchOffset(int value) {
        this.fetchOffset = value;
    }

    /**
     * Gets the value of the fetchSize property.
     * 
     */
    public int getFetchSize() {
        return fetchSize;
    }

    /**
     * Sets the value of the fetchSize property.
     * 
     */
    public void setFetchSize(int value) {
        this.fetchSize = value;
    }

    /**
     * Gets the value of the readSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the readSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReadSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * 
     * 
     */
    public List<Field> getReadSet() {
        if (readSet == null) {
            readSet = new ArrayList<Field>();
        }
        return this.readSet;
    }

    /**
     * Gets the value of the constraint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the constraint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConstraint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Constraint }
     * 
     * 
     */
    public List<Constraint> getConstraint() {
        if (constraint == null) {
            constraint = new ArrayList<Constraint>();
        }
        return this.constraint;
    }

    /**
     * Gets the value of the sortBy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sortBy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSortBy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SortBy }
     * 
     * 
     */
    public List<SortBy> getSortBy() {
        if (sortBy == null) {
            sortBy = new ArrayList<SortBy>();
        }
        return this.sortBy;
    }

    /**
     * Gets the value of the distribution property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the distribution property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDistribution().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbstractDistributionRequest }
     * 
     * 
     */
    public List<AbstractDistributionRequest> getDistribution() {
        if (distribution == null) {
            distribution = new ArrayList<AbstractDistributionRequest>();
        }
        return this.distribution;
    }

    /**
     * Gets the value of the bucket property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bucket property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBucket().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BucketRequest }
     * 
     * 
     */
    public List<BucketRequest> getBucket() {
        if (bucket == null) {
            bucket = new ArrayList<BucketRequest>();
        }
        return this.bucket;
    }

    /**
     * Gets the value of the permutation property.
     * 
     * @return
     *     possible object is
     *     {@link PermutationRequest }
     *     
     */
    public PermutationRequest getPermutation() {
        return permutation;
    }

    /**
     * Sets the value of the permutation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermutationRequest }
     *     
     */
    public void setPermutation(PermutationRequest value) {
        this.permutation = value;
    }

    /**
     * Gets the value of the uniqueBy property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueBy }
     *     
     */
    public UniqueBy getUniqueBy() {
        return uniqueBy;
    }

    /**
     * Sets the value of the uniqueBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueBy }
     *     
     */
    public void setUniqueBy(UniqueBy value) {
        this.uniqueBy = value;
    }

    /**
     * Gets the value of the blendBy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the blendBy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBlendBy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BlendBy }
     * 
     * 
     */
    public List<BlendBy> getBlendBy() {
        if (blendBy == null) {
            blendBy = new ArrayList<BlendBy>();
        }
        return this.blendBy;
    }

    /**
     * Gets the value of the includeDiagnosticInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeDiagnosticInfo() {
        return includeDiagnosticInfo;
    }

    /**
     * Sets the value of the includeDiagnosticInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeDiagnosticInfo(Boolean value) {
        this.includeDiagnosticInfo = value;
    }

    /**
     * Gets the value of the dfn property.
     * 
     * @return
     *     possible object is
     *     {@link DominantProductTypeRequest }
     *     
     */
    public DominantProductTypeRequest getDfn() {
        return dfn;
    }

    /**
     * Sets the value of the dfn property.
     * 
     * @param value
     *     allowed object is
     *     {@link DominantProductTypeRequest }
     *     
     */
    public void setDfn(DominantProductTypeRequest value) {
        this.dfn = value;
    }

}
