//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FitmentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FitmentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NONE"/>
 *     &lt;enumeration value="BY_APPLICATION"/>
 *     &lt;enumeration value="BY_SPECIFICATION"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FitmentType")
@XmlEnum
public enum FitmentType {


    /**
     * No Fitment
     * 
     */
    NONE,

    /**
     * Fitment by Application
     * 
     */
    BY_APPLICATION,

    /**
     * Fitment by Specification
     * 
     */
    BY_SPECIFICATION;

    public String value() {
        return name();
    }

    public static FitmentType fromValue(String v) {
        return valueOf(v);
    }

}
