//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FitmentResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FitmentResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.ebay.com/marketplace/search/v1/services}FitmentType"/>
 *         &lt;element name="parameter" type="{http://www.ebay.com/marketplace/search/v1/services}FitmentParameter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="runSpec" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hasSpec" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="truncateSpec" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="truncateApp" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FitmentResponse", propOrder = {
    "type",
    "parameter",
    "runSpec",
    "hasSpec",
    "truncateSpec",
    "truncateApp"
})
public class FitmentResponse {

    @XmlElement(required = true)
    protected FitmentType type;
    protected List<FitmentParameter> parameter;
    protected boolean runSpec;
    protected boolean hasSpec;
    protected boolean truncateSpec;
    protected boolean truncateApp;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link FitmentType }
     *     
     */
    public FitmentType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link FitmentType }
     *     
     */
    public void setType(FitmentType value) {
        this.type = value;
    }

    /**
     * Gets the value of the parameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FitmentParameter }
     * 
     * 
     */
    public List<FitmentParameter> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<FitmentParameter>();
        }
        return this.parameter;
    }

    /**
     * Gets the value of the runSpec property.
     * 
     */
    public boolean isRunSpec() {
        return runSpec;
    }

    /**
     * Sets the value of the runSpec property.
     * 
     */
    public void setRunSpec(boolean value) {
        this.runSpec = value;
    }

    /**
     * Gets the value of the hasSpec property.
     * 
     */
    public boolean isHasSpec() {
        return hasSpec;
    }

    /**
     * Sets the value of the hasSpec property.
     * 
     */
    public void setHasSpec(boolean value) {
        this.hasSpec = value;
    }

    /**
     * Gets the value of the truncateSpec property.
     * 
     */
    public boolean isTruncateSpec() {
        return truncateSpec;
    }

    /**
     * Sets the value of the truncateSpec property.
     * 
     */
    public void setTruncateSpec(boolean value) {
        this.truncateSpec = value;
    }

    /**
     * Gets the value of the truncateApp property.
     * 
     */
    public boolean isTruncateApp() {
        return truncateApp;
    }

    /**
     * Sets the value of the truncateApp property.
     * 
     */
    public void setTruncateApp(boolean value) {
        this.truncateApp = value;
    }

}
