//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 						Use this sort type to get similar image items
 * 						based on an image value
 * 					
 * 
 * <p>Java class for ImageSimilaritySortTypeBySignature complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImageSimilaritySortTypeBySignature">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ebay.com/marketplace/search/v1/services}BaseImageSimilaritySortTypeBase">
 *       &lt;sequence>
 *         &lt;element name="digestValueData" type="{http://www.ebay.com/marketplace/search/v1/services}DigestValueData" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageSimilaritySortTypeBySignature", propOrder = {
    "digestValueData"
})
public class ImageSimilaritySortTypeBySignature
    extends BaseImageSimilaritySortTypeBase
{

    @XmlElement(required = true)
    protected List<DigestValueData> digestValueData;

    /**
     * Gets the value of the digestValueData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the digestValueData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDigestValueData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DigestValueData }
     * 
     * 
     */
    public List<DigestValueData> getDigestValueData() {
        if (digestValueData == null) {
            digestValueData = new ArrayList<DigestValueData>();
        }
        return this.digestValueData;
    }

}
