//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemSearchScopeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ItemSearchScopeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ActiveTitle"/>
 *     &lt;enumeration value="ActiveTitleAndDescription"/>
 *     &lt;enumeration value="CompletedTitle"/>
 *     &lt;enumeration value="ImageSearchActive"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ItemSearchScopeEnum")
@XmlEnum
public enum ItemSearchScopeEnum {


    /**
     * 
     * 								Active items, Title search only.
     * 							
     * 
     */
    @XmlEnumValue("ActiveTitle")
    ACTIVE_TITLE("ActiveTitle"),

    /**
     * 
     * 								Active items, Title and description
     * 								search.
     * 							
     * 
     */
    @XmlEnumValue("ActiveTitleAndDescription")
    ACTIVE_TITLE_AND_DESCRIPTION("ActiveTitleAndDescription"),

    /**
     * 
     * 								Completed items, Title search only.
     * 							
     * 
     */
    @XmlEnumValue("CompletedTitle")
    COMPLETED_TITLE("CompletedTitle"),

    /**
     * 
     * 								Similar image items, active item search
     * 								only.
     * 							
     * 
     */
    @XmlEnumValue("ImageSearchActive")
    IMAGE_SEARCH_ACTIVE("ImageSearchActive");
    private final String value;

    ItemSearchScopeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ItemSearchScopeEnum fromValue(String v) {
        for (ItemSearchScopeEnum c: ItemSearchScopeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
