//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemSortTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ItemSortTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CurrentPrice"/>
 *     &lt;enumeration value="BINPrice"/>
 *     &lt;enumeration value="EndTime"/>
 *     &lt;enumeration value="StartTime"/>
 *     &lt;enumeration value="Bucket"/>
 *     &lt;enumeration value="Random"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ItemSortTypeEnum")
@XmlEnum
public enum ItemSortTypeEnum {


    /**
     * 
     * 								sort by the current price of items.
     * 							
     * 
     */
    @XmlEnumValue("CurrentPrice")
    CURRENT_PRICE("CurrentPrice"),

    /**
     * 
     * 								sort by the BIN price of items.
     * 							
     * 
     */
    @XmlEnumValue("BINPrice")
    BIN_PRICE("BINPrice"),

    /**
     * 
     * 								sort by the End Time of items.
     * 							
     * 
     */
    @XmlEnumValue("EndTime")
    END_TIME("EndTime"),

    /**
     * 
     * 								sort by the Start Time of items.
     * 							
     * 
     */
    @XmlEnumValue("StartTime")
    START_TIME("StartTime"),

    /**
     * 
     * 								Bucket sort. Clients needs to define
     * 								BucketRequet in the request.
     * 							
     * 
     */
    @XmlEnumValue("Bucket")
    BUCKET("Bucket"),

    /**
     * 
     * 								random sort, no particular order is
     * 								used.
     * 							
     * 
     */
    @XmlEnumValue("Random")
    RANDOM("Random");
    private final String value;

    ItemSortTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ItemSortTypeEnum fromValue(String v) {
        for (ItemSortTypeEnum c: ItemSortTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
