//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 						This is an abstract type which defines the
 * 						expression with Boolean value. It has
 * 						StategyLogicalExpression,
 * 						SimpleLogicalExpression,
 * 						KeywordLogicalExpression and
 * 						CompositeLogicalExpression
 * 					
 * 
 * <p>Java class for LogicalExpression complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LogicalExpression">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="compositeLogicalExpression" type="{http://www.ebay.com/marketplace/search/v1/services}CompositeLogicalExpression"/>
 *         &lt;element name="keywordLogicalExpression" type="{http://www.ebay.com/marketplace/search/v1/services}KeywordLogicalExpression"/>
 *         &lt;element name="simpleLogicalExpression" type="{http://www.ebay.com/marketplace/search/v1/services}SimpleLogicalExpression"/>
 *         &lt;element name="strategyLogicalExpression" type="{http://www.ebay.com/marketplace/search/v1/services}StrategyLogicalExpression"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LogicalExpression", propOrder = {
    "compositeLogicalExpression",
    "keywordLogicalExpression",
    "simpleLogicalExpression",
    "strategyLogicalExpression"
})
public class LogicalExpression {

    protected CompositeLogicalExpression compositeLogicalExpression;
    protected KeywordLogicalExpression keywordLogicalExpression;
    protected SimpleLogicalExpression simpleLogicalExpression;
    protected StrategyLogicalExpression strategyLogicalExpression;

    /**
     * Gets the value of the compositeLogicalExpression property.
     * 
     * @return
     *     possible object is
     *     {@link CompositeLogicalExpression }
     *     
     */
    public CompositeLogicalExpression getCompositeLogicalExpression() {
        return compositeLogicalExpression;
    }

    /**
     * Sets the value of the compositeLogicalExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositeLogicalExpression }
     *     
     */
    public void setCompositeLogicalExpression(CompositeLogicalExpression value) {
        this.compositeLogicalExpression = value;
    }

    /**
     * Gets the value of the keywordLogicalExpression property.
     * 
     * @return
     *     possible object is
     *     {@link KeywordLogicalExpression }
     *     
     */
    public KeywordLogicalExpression getKeywordLogicalExpression() {
        return keywordLogicalExpression;
    }

    /**
     * Sets the value of the keywordLogicalExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeywordLogicalExpression }
     *     
     */
    public void setKeywordLogicalExpression(KeywordLogicalExpression value) {
        this.keywordLogicalExpression = value;
    }

    /**
     * Gets the value of the simpleLogicalExpression property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleLogicalExpression }
     *     
     */
    public SimpleLogicalExpression getSimpleLogicalExpression() {
        return simpleLogicalExpression;
    }

    /**
     * Sets the value of the simpleLogicalExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleLogicalExpression }
     *     
     */
    public void setSimpleLogicalExpression(SimpleLogicalExpression value) {
        this.simpleLogicalExpression = value;
    }

    /**
     * Gets the value of the strategyLogicalExpression property.
     * 
     * @return
     *     possible object is
     *     {@link StrategyLogicalExpression }
     *     
     */
    public StrategyLogicalExpression getStrategyLogicalExpression() {
        return strategyLogicalExpression;
    }

    /**
     * Sets the value of the strategyLogicalExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link StrategyLogicalExpression }
     *     
     */
    public void setStrategyLogicalExpression(StrategyLogicalExpression value) {
        this.strategyLogicalExpression = value;
    }

}
