//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 						This the abstract type of numeric expression.
 * 					
 * 
 * <p>Java class for NumericExpression complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NumericExpression">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="aggregatenumericExpression" type="{http://www.ebay.com/marketplace/search/v1/services}AggregateNumericExpression"/>
 *         &lt;element name="simplenumericExpression" type="{http://www.ebay.com/marketplace/search/v1/services}SimpleNumericExpression"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NumericExpression", propOrder = {
    "aggregatenumericExpression",
    "simplenumericExpression"
})
public class NumericExpression {

    protected AggregateNumericExpression aggregatenumericExpression;
    protected SimpleNumericExpression simplenumericExpression;

    /**
     * Gets the value of the aggregatenumericExpression property.
     * 
     * @return
     *     possible object is
     *     {@link AggregateNumericExpression }
     *     
     */
    public AggregateNumericExpression getAggregatenumericExpression() {
        return aggregatenumericExpression;
    }

    /**
     * Sets the value of the aggregatenumericExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link AggregateNumericExpression }
     *     
     */
    public void setAggregatenumericExpression(AggregateNumericExpression value) {
        this.aggregatenumericExpression = value;
    }

    /**
     * Gets the value of the simplenumericExpression property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleNumericExpression }
     *     
     */
    public SimpleNumericExpression getSimplenumericExpression() {
        return simplenumericExpression;
    }

    /**
     * Sets the value of the simplenumericExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleNumericExpression }
     *     
     */
    public void setSimplenumericExpression(SimpleNumericExpression value) {
        this.simplenumericExpression = value;
    }

}
