//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ebay.marketplace.search.v1.services package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetVersionRequest_QNAME = new QName("http://www.ebay.com/marketplace/search/v1/services", "getVersionRequest");
    private final static QName _FindItemsRequest_QNAME = new QName("http://www.ebay.com/marketplace/search/v1/services", "findItemsRequest");
    private final static QName _FindItemsResponse_QNAME = new QName("http://www.ebay.com/marketplace/search/v1/services", "findItemsResponse");
    private final static QName _FindItemsByIdsResponse_QNAME = new QName("http://www.ebay.com/marketplace/search/v1/services", "findItemsByIdsResponse");
    private final static QName _FindItemsByIdsRequest_QNAME = new QName("http://www.ebay.com/marketplace/search/v1/services", "findItemsByIdsRequest");
    private final static QName _GetVersionResponse_QNAME = new QName("http://www.ebay.com/marketplace/search/v1/services", "getVersionResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ebay.marketplace.search.v1.services
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FitmentFieldValue }
     * 
     */
    public FitmentFieldValue createFitmentFieldValue() {
        return new FitmentFieldValue();
    }

    /**
     * Create an instance of {@link KeywordLogicalExpression }
     * 
     */
    public KeywordLogicalExpression createKeywordLogicalExpression() {
        return new KeywordLogicalExpression();
    }

    /**
     * Create an instance of {@link ItemSortType }
     * 
     */
    public ItemSortType createItemSortType() {
        return new ItemSortType();
    }

    /**
     * Create an instance of {@link PermutationRequest }
     * 
     */
    public PermutationRequest createPermutationRequest() {
        return new PermutationRequest();
    }

    /**
     * Create an instance of {@link DiagnosticInfo }
     * 
     */
    public DiagnosticInfo createDiagnosticInfo() {
        return new DiagnosticInfo();
    }

    /**
     * Create an instance of {@link LongFieldValue }
     * 
     */
    public LongFieldValue createLongFieldValue() {
        return new LongFieldValue();
    }

    /**
     * Create an instance of {@link AbstractDistributionResponse }
     * 
     */
    public AbstractDistributionResponse createAbstractDistributionResponse() {
        return new AbstractDistributionResponse();
    }

    /**
     * Create an instance of {@link DoubleOperand }
     * 
     */
    public DoubleOperand createDoubleOperand() {
        return new DoubleOperand();
    }

    /**
     * Create an instance of {@link FindItemsRequest }
     * 
     */
    public FindItemsRequest createFindItemsRequest() {
        return new FindItemsRequest();
    }

    /**
     * Create an instance of {@link AbstractDistributionRequest }
     * 
     */
    public AbstractDistributionRequest createAbstractDistributionRequest() {
        return new AbstractDistributionRequest();
    }

    /**
     * Create an instance of {@link DoubleFieldValue }
     * 
     */
    public DoubleFieldValue createDoubleFieldValue() {
        return new DoubleFieldValue();
    }

    /**
     * Create an instance of {@link ResultSummaryInfo }
     * 
     */
    public ResultSummaryInfo createResultSummaryInfo() {
        return new ResultSummaryInfo();
    }

    /**
     * Create an instance of {@link ErrorMessage }
     * 
     */
    public ErrorMessage createErrorMessage() {
        return new ErrorMessage();
    }

    /**
     * Create an instance of {@link SimpleCountDistributionRecord }
     * 
     */
    public SimpleCountDistributionRecord createSimpleCountDistributionRecord() {
        return new SimpleCountDistributionRecord();
    }

    /**
     * Create an instance of {@link RangeValue }
     * 
     */
    public RangeValue createRangeValue() {
        return new RangeValue();
    }

    /**
     * Create an instance of {@link DistanceSortType }
     * 
     */
    public DistanceSortType createDistanceSortType() {
        return new DistanceSortType();
    }

    /**
     * Create an instance of {@link SellerLogoFieldValue }
     * 
     */
    public SellerLogoFieldValue createSellerLogoFieldValue() {
        return new SellerLogoFieldValue();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link FindItemsByIdsRequest }
     * 
     */
    public FindItemsByIdsRequest createFindItemsByIdsRequest() {
        return new FindItemsByIdsRequest();
    }

    /**
     * Create an instance of {@link TraitFieldValue }
     * 
     */
    public TraitFieldValue createTraitFieldValue() {
        return new TraitFieldValue();
    }

    /**
     * Create an instance of {@link Operand }
     * 
     */
    public Operand createOperand() {
        return new Operand();
    }

    /**
     * Create an instance of {@link BestMatchSortType }
     * 
     */
    public BestMatchSortType createBestMatchSortType() {
        return new BestMatchSortType();
    }

    /**
     * Create an instance of {@link PricePlusShippingSortType }
     * 
     */
    public PricePlusShippingSortType createPricePlusShippingSortType() {
        return new PricePlusShippingSortType();
    }

    /**
     * Create an instance of {@link SimpleCountDistributionRequest }
     * 
     */
    public SimpleCountDistributionRequest createSimpleCountDistributionRequest() {
        return new SimpleCountDistributionRequest();
    }

    /**
     * Create an instance of {@link DistributionResponse }
     * 
     */
    public DistributionResponse createDistributionResponse() {
        return new DistributionResponse();
    }

    /**
     * Create an instance of {@link CompositeLogicalExpression }
     * 
     */
    public CompositeLogicalExpression createCompositeLogicalExpression() {
        return new CompositeLogicalExpression();
    }

    /**
     * Create an instance of {@link DistributionSortBy }
     * 
     */
    public DistributionSortBy createDistributionSortBy() {
        return new DistributionSortBy();
    }

    /**
     * Create an instance of {@link BucketResponse }
     * 
     */
    public BucketResponse createBucketResponse() {
        return new BucketResponse();
    }

    /**
     * Create an instance of {@link SimpleCountDistributionResponse }
     * 
     */
    public SimpleCountDistributionResponse createSimpleCountDistributionResponse() {
        return new SimpleCountDistributionResponse();
    }

    /**
     * Create an instance of {@link SearchRecord }
     * 
     */
    public SearchRecord createSearchRecord() {
        return new SearchRecord();
    }

    /**
     * Create an instance of {@link FindItemsResponse }
     * 
     */
    public FindItemsResponse createFindItemsResponse() {
        return new FindItemsResponse();
    }

    /**
     * Create an instance of {@link DateFieldValue }
     * 
     */
    public DateFieldValue createDateFieldValue() {
        return new DateFieldValue();
    }

    /**
     * Create an instance of {@link FitmentParameter }
     * 
     */
    public FitmentParameter createFitmentParameter() {
        return new FitmentParameter();
    }

    /**
     * Create an instance of {@link SimpleLogicalExpression }
     * 
     */
    public SimpleLogicalExpression createSimpleLogicalExpression() {
        return new SimpleLogicalExpression();
    }

    /**
     * Create an instance of {@link BestMatchSortTypeBase }
     * 
     */
    public BestMatchSortTypeBase createBestMatchSortTypeBase() {
        return new BestMatchSortTypeBase();
    }

    /**
     * Create an instance of {@link Constraint }
     * 
     */
    public Constraint createConstraint() {
        return new Constraint();
    }

    /**
     * Create an instance of {@link AggregateNumericExpression }
     * 
     */
    public AggregateNumericExpression createAggregateNumericExpression() {
        return new AggregateNumericExpression();
    }

    /**
     * Create an instance of {@link TokenOperand }
     * 
     */
    public TokenOperand createTokenOperand() {
        return new TokenOperand();
    }

    /**
     * Create an instance of {@link ImageSimilaritySortTypeByItem }
     * 
     */
    public ImageSimilaritySortTypeByItem createImageSimilaritySortTypeByItem() {
        return new ImageSimilaritySortTypeByItem();
    }

    /**
     * Create an instance of {@link DominantProductTypeResponse }
     * 
     */
    public DominantProductTypeResponse createDominantProductTypeResponse() {
        return new DominantProductTypeResponse();
    }

    /**
     * Create an instance of {@link LongOperand }
     * 
     */
    public LongOperand createLongOperand() {
        return new LongOperand();
    }

    /**
     * Create an instance of {@link FieldOperand }
     * 
     */
    public FieldOperand createFieldOperand() {
        return new FieldOperand();
    }

    /**
     * Create an instance of {@link ImageSimilaritySortTypeBySignature }
     * 
     */
    public ImageSimilaritySortTypeBySignature createImageSimilaritySortTypeBySignature() {
        return new ImageSimilaritySortTypeBySignature();
    }

    /**
     * Create an instance of {@link DigestTypeData }
     * 
     */
    public DigestTypeData createDigestTypeData() {
        return new DigestTypeData();
    }

    /**
     * Create an instance of {@link ColorDimensionWeight }
     * 
     */
    public ColorDimensionWeight createColorDimensionWeight() {
        return new ColorDimensionWeight();
    }

    /**
     * Create an instance of {@link StringFieldValue }
     * 
     */
    public StringFieldValue createStringFieldValue() {
        return new StringFieldValue();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link SimpleNumericExpression }
     * 
     */
    public SimpleNumericExpression createSimpleNumericExpression() {
        return new SimpleNumericExpression();
    }

    /**
     * Create an instance of {@link ProductTypeCoverage }
     * 
     */
    public ProductTypeCoverage createProductTypeCoverage() {
        return new ProductTypeCoverage();
    }

    /**
     * Create an instance of {@link LogicalExpression }
     * 
     */
    public LogicalExpression createLogicalExpression() {
        return new LogicalExpression();
    }

    /**
     * Create an instance of {@link DominantProductTypeRequest }
     * 
     */
    public DominantProductTypeRequest createDominantProductTypeRequest() {
        return new DominantProductTypeRequest();
    }

    /**
     * Create an instance of {@link PermutationResponse }
     * 
     */
    public PermutationResponse createPermutationResponse() {
        return new PermutationResponse();
    }

    /**
     * Create an instance of {@link DateOperand }
     * 
     */
    public DateOperand createDateOperand() {
        return new DateOperand();
    }

    /**
     * Create an instance of {@link MoneyOperand }
     * 
     */
    public MoneyOperand createMoneyOperand() {
        return new MoneyOperand();
    }

    /**
     * Create an instance of {@link StrategyLogicalExpression }
     * 
     */
    public StrategyLogicalExpression createStrategyLogicalExpression() {
        return new StrategyLogicalExpression();
    }

    /**
     * Create an instance of {@link UniqueBy }
     * 
     */
    public UniqueBy createUniqueBy() {
        return new UniqueBy();
    }

    /**
     * Create an instance of {@link FindItemsByIdsResponse }
     * 
     */
    public FindItemsByIdsResponse createFindItemsByIdsResponse() {
        return new FindItemsByIdsResponse();
    }

    /**
     * Create an instance of {@link NumericExpression }
     * 
     */
    public NumericExpression createNumericExpression() {
        return new NumericExpression();
    }

    /**
     * Create an instance of {@link ErrorData }
     * 
     */
    public ErrorData createErrorData() {
        return new ErrorData();
    }

    /**
     * Create an instance of {@link EnumerationValue }
     * 
     */
    public EnumerationValue createEnumerationValue() {
        return new EnumerationValue();
    }

    /**
     * Create an instance of {@link ErrorParameter }
     * 
     */
    public ErrorParameter createErrorParameter() {
        return new ErrorParameter();
    }

    /**
     * Create an instance of {@link BaseImageSimilaritySortType }
     * 
     */
    public BaseImageSimilaritySortType createBaseImageSimilaritySortType() {
        return new BaseImageSimilaritySortType();
    }

    /**
     * Create an instance of {@link SortBy }
     * 
     */
    public SortBy createSortBy() {
        return new SortBy();
    }

    /**
     * Create an instance of {@link FieldValuesPair }
     * 
     */
    public FieldValuesPair createFieldValuesPair() {
        return new FieldValuesPair();
    }

    /**
     * Create an instance of {@link GetVersionResponse }
     * 
     */
    public GetVersionResponse createGetVersionResponse() {
        return new GetVersionResponse();
    }

    /**
     * Create an instance of {@link BucketRequest }
     * 
     */
    public BucketRequest createBucketRequest() {
        return new BucketRequest();
    }

    /**
     * Create an instance of {@link BooleanFieldValue }
     * 
     */
    public BooleanFieldValue createBooleanFieldValue() {
        return new BooleanFieldValue();
    }

    /**
     * Create an instance of {@link DigestValueData }
     * 
     */
    public DigestValueData createDigestValueData() {
        return new DigestValueData();
    }

    /**
     * Create an instance of {@link FitmentResponse }
     * 
     */
    public FitmentResponse createFitmentResponse() {
        return new FitmentResponse();
    }

    /**
     * Create an instance of {@link ServiceContext }
     * 
     */
    public ServiceContext createServiceContext() {
        return new ServiceContext();
    }

    /**
     * Create an instance of {@link ShippingCostFieldValue }
     * 
     */
    public ShippingCostFieldValue createShippingCostFieldValue() {
        return new ShippingCostFieldValue();
    }

    /**
     * Create an instance of {@link MoneyFieldValue }
     * 
     */
    public MoneyFieldValue createMoneyFieldValue() {
        return new MoneyFieldValue();
    }

    /**
     * Create an instance of {@link FieldValue }
     * 
     */
    public FieldValue createFieldValue() {
        return new FieldValue();
    }

    /**
     * Create an instance of {@link Member }
     * 
     */
    public Member createMember() {
        return new Member();
    }

    /**
     * Create an instance of {@link BaseServiceContext }
     * 
     */
    public BaseServiceContext createBaseServiceContext() {
        return new BaseServiceContext();
    }

    /**
     * Create an instance of {@link BlendBy }
     * 
     */
    public BlendBy createBlendBy() {
        return new BlendBy();
    }

    /**
     * Create an instance of {@link Expression }
     * 
     */
    public Expression createExpression() {
        return new Expression();
    }

    /**
     * Create an instance of {@link GetVersionRequest }
     * 
     */
    public GetVersionRequest createGetVersionRequest() {
        return new GetVersionRequest();
    }

    /**
     * Create an instance of {@link DistributionField }
     * 
     */
    public DistributionField createDistributionField() {
        return new DistributionField();
    }

    /**
     * Create an instance of {@link DistributionRequest }
     * 
     */
    public DistributionRequest createDistributionRequest() {
        return new DistributionRequest();
    }

    /**
     * Create an instance of {@link DistributionRecord }
     * 
     */
    public DistributionRecord createDistributionRecord() {
        return new DistributionRecord();
    }

    /**
     * Create an instance of {@link SortType }
     * 
     */
    public SortType createSortType() {
        return new SortType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetVersionRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebay.com/marketplace/search/v1/services", name = "getVersionRequest")
    public JAXBElement<GetVersionRequest> createGetVersionRequest(GetVersionRequest value) {
        return new JAXBElement<GetVersionRequest>(_GetVersionRequest_QNAME, GetVersionRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindItemsRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebay.com/marketplace/search/v1/services", name = "findItemsRequest")
    public JAXBElement<FindItemsRequest> createFindItemsRequest(FindItemsRequest value) {
        return new JAXBElement<FindItemsRequest>(_FindItemsRequest_QNAME, FindItemsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindItemsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebay.com/marketplace/search/v1/services", name = "findItemsResponse")
    public JAXBElement<FindItemsResponse> createFindItemsResponse(FindItemsResponse value) {
        return new JAXBElement<FindItemsResponse>(_FindItemsResponse_QNAME, FindItemsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindItemsByIdsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebay.com/marketplace/search/v1/services", name = "findItemsByIdsResponse")
    public JAXBElement<FindItemsByIdsResponse> createFindItemsByIdsResponse(FindItemsByIdsResponse value) {
        return new JAXBElement<FindItemsByIdsResponse>(_FindItemsByIdsResponse_QNAME, FindItemsByIdsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindItemsByIdsRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebay.com/marketplace/search/v1/services", name = "findItemsByIdsRequest")
    public JAXBElement<FindItemsByIdsRequest> createFindItemsByIdsRequest(FindItemsByIdsRequest value) {
        return new JAXBElement<FindItemsByIdsRequest>(_FindItemsByIdsRequest_QNAME, FindItemsByIdsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetVersionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebay.com/marketplace/search/v1/services", name = "getVersionResponse")
    public JAXBElement<GetVersionResponse> createGetVersionResponse(GetVersionResponse value) {
        return new JAXBElement<GetVersionResponse>(_GetVersionResponse_QNAME, GetVersionResponse.class, null, value);
    }

}
