//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 						This is the abstract operand.
 * 					
 * 
 * <p>Java class for Operand complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Operand">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="dateOperand" type="{http://www.ebay.com/marketplace/search/v1/services}DateOperand"/>
 *         &lt;element name="doubleOperand" type="{http://www.ebay.com/marketplace/search/v1/services}DoubleOperand"/>
 *         &lt;element name="fieldOperand" type="{http://www.ebay.com/marketplace/search/v1/services}FieldOperand"/>
 *         &lt;element name="longOperand" type="{http://www.ebay.com/marketplace/search/v1/services}LongOperand"/>
 *         &lt;element name="moneyOperand" type="{http://www.ebay.com/marketplace/search/v1/services}MoneyOperand"/>
 *         &lt;element name="tokenOperand" type="{http://www.ebay.com/marketplace/search/v1/services}TokenOperand"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Operand", propOrder = {
    "dateOperand",
    "doubleOperand",
    "fieldOperand",
    "longOperand",
    "moneyOperand",
    "tokenOperand"
})
public class Operand {

    protected DateOperand dateOperand;
    protected DoubleOperand doubleOperand;
    protected FieldOperand fieldOperand;
    protected LongOperand longOperand;
    protected MoneyOperand moneyOperand;
    protected TokenOperand tokenOperand;

    /**
     * Gets the value of the dateOperand property.
     * 
     * @return
     *     possible object is
     *     {@link DateOperand }
     *     
     */
    public DateOperand getDateOperand() {
        return dateOperand;
    }

    /**
     * Sets the value of the dateOperand property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateOperand }
     *     
     */
    public void setDateOperand(DateOperand value) {
        this.dateOperand = value;
    }

    /**
     * Gets the value of the doubleOperand property.
     * 
     * @return
     *     possible object is
     *     {@link DoubleOperand }
     *     
     */
    public DoubleOperand getDoubleOperand() {
        return doubleOperand;
    }

    /**
     * Sets the value of the doubleOperand property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoubleOperand }
     *     
     */
    public void setDoubleOperand(DoubleOperand value) {
        this.doubleOperand = value;
    }

    /**
     * Gets the value of the fieldOperand property.
     * 
     * @return
     *     possible object is
     *     {@link FieldOperand }
     *     
     */
    public FieldOperand getFieldOperand() {
        return fieldOperand;
    }

    /**
     * Sets the value of the fieldOperand property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldOperand }
     *     
     */
    public void setFieldOperand(FieldOperand value) {
        this.fieldOperand = value;
    }

    /**
     * Gets the value of the longOperand property.
     * 
     * @return
     *     possible object is
     *     {@link LongOperand }
     *     
     */
    public LongOperand getLongOperand() {
        return longOperand;
    }

    /**
     * Sets the value of the longOperand property.
     * 
     * @param value
     *     allowed object is
     *     {@link LongOperand }
     *     
     */
    public void setLongOperand(LongOperand value) {
        this.longOperand = value;
    }

    /**
     * Gets the value of the moneyOperand property.
     * 
     * @return
     *     possible object is
     *     {@link MoneyOperand }
     *     
     */
    public MoneyOperand getMoneyOperand() {
        return moneyOperand;
    }

    /**
     * Sets the value of the moneyOperand property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoneyOperand }
     *     
     */
    public void setMoneyOperand(MoneyOperand value) {
        this.moneyOperand = value;
    }

    /**
     * Gets the value of the tokenOperand property.
     * 
     * @return
     *     possible object is
     *     {@link TokenOperand }
     *     
     */
    public TokenOperand getTokenOperand() {
        return tokenOperand;
    }

    /**
     * Sets the value of the tokenOperand property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenOperand }
     *     
     */
    public void setTokenOperand(TokenOperand value) {
        this.tokenOperand = value;
    }

}
