//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ebay.com/marketplace/search/v1/services", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ebay.marketplace.search.v1.services;
