//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 						This is the type to keep product type coverage
 * 						information
 * 					
 * 
 * <p>Java class for ProductTypeCoverage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductTypeCoverage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="supplyScore" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="demandScore" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="aggregateScore" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductTypeCoverage", propOrder = {
    "name",
    "supplyScore",
    "demandScore",
    "aggregateScore"
})
public class ProductTypeCoverage {

    @XmlElement(required = true)
    protected String name;
    protected double supplyScore;
    protected Double demandScore;
    protected double aggregateScore;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the supplyScore property.
     * 
     */
    public double getSupplyScore() {
        return supplyScore;
    }

    /**
     * Sets the value of the supplyScore property.
     * 
     */
    public void setSupplyScore(double value) {
        this.supplyScore = value;
    }

    /**
     * Gets the value of the demandScore property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDemandScore() {
        return demandScore;
    }

    /**
     * Sets the value of the demandScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDemandScore(Double value) {
        this.demandScore = value;
    }

    /**
     * Gets the value of the aggregateScore property.
     * 
     */
    public double getAggregateScore() {
        return aggregateScore;
    }

    /**
     * Sets the value of the aggregateScore property.
     * 
     */
    public void setAggregateScore(double value) {
        this.aggregateScore = value;
    }

}
