//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 						This type contains aggregated shipping
 * 						information for an item.
 * 					
 * 
 * <p>Java class for ShippingCostFieldValue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShippingCostFieldValue">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ebay.com/marketplace/search/v1/services}FieldValueBase">
 *       &lt;sequence>
 *         &lt;element name="shipCost" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="insuranceCost" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mailClass" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="errorCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="shipCostWithInsurance" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="shippingZone" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShippingCostFieldValue", propOrder = {
    "shipCost",
    "insuranceCost",
    "mailClass",
    "errorCode",
    "shipCostWithInsurance",
    "shippingZone"
})
public class ShippingCostFieldValue
    extends FieldValueBase
{

    protected double shipCost;
    protected double insuranceCost;
    protected int mailClass;
    protected int errorCode;
    protected double shipCostWithInsurance;
    protected int shippingZone;

    /**
     * Gets the value of the shipCost property.
     * 
     */
    public double getShipCost() {
        return shipCost;
    }

    /**
     * Sets the value of the shipCost property.
     * 
     */
    public void setShipCost(double value) {
        this.shipCost = value;
    }

    /**
     * Gets the value of the insuranceCost property.
     * 
     */
    public double getInsuranceCost() {
        return insuranceCost;
    }

    /**
     * Sets the value of the insuranceCost property.
     * 
     */
    public void setInsuranceCost(double value) {
        this.insuranceCost = value;
    }

    /**
     * Gets the value of the mailClass property.
     * 
     */
    public int getMailClass() {
        return mailClass;
    }

    /**
     * Sets the value of the mailClass property.
     * 
     */
    public void setMailClass(int value) {
        this.mailClass = value;
    }

    /**
     * Gets the value of the errorCode property.
     * 
     */
    public int getErrorCode() {
        return errorCode;
    }

    /**
     * Sets the value of the errorCode property.
     * 
     */
    public void setErrorCode(int value) {
        this.errorCode = value;
    }

    /**
     * Gets the value of the shipCostWithInsurance property.
     * 
     */
    public double getShipCostWithInsurance() {
        return shipCostWithInsurance;
    }

    /**
     * Sets the value of the shipCostWithInsurance property.
     * 
     */
    public void setShipCostWithInsurance(double value) {
        this.shipCostWithInsurance = value;
    }

    /**
     * Gets the value of the shippingZone property.
     * 
     */
    public int getShippingZone() {
        return shippingZone;
    }

    /**
     * Sets the value of the shippingZone property.
     * 
     */
    public void setShippingZone(int value) {
        this.shippingZone = value;
    }

}
