//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				SortBy is used to define the order of result entries.
 * 			
 * 
 * <p>Java class for SortBy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SortBy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="sortMember" type="{http://www.ebay.com/marketplace/search/v1/services}Member" minOccurs="0"/>
 *           &lt;element name="sortExpression" type="{http://www.ebay.com/marketplace/search/v1/services}Expression" minOccurs="0"/>
 *           &lt;element name="sortType" type="{http://www.ebay.com/marketplace/search/v1/services}SortType" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="sortOrder" type="{http://www.ebay.com/marketplace/search/v1/services}SortOrder" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SortBy", propOrder = {
    "sortMember",
    "sortExpression",
    "sortType",
    "sortOrder"
})
public class SortBy {

    protected Member sortMember;
    protected Expression sortExpression;
    protected SortType sortType;
    protected SortOrder sortOrder;

    /**
     * Gets the value of the sortMember property.
     * 
     * @return
     *     possible object is
     *     {@link Member }
     *     
     */
    public Member getSortMember() {
        return sortMember;
    }

    /**
     * Sets the value of the sortMember property.
     * 
     * @param value
     *     allowed object is
     *     {@link Member }
     *     
     */
    public void setSortMember(Member value) {
        this.sortMember = value;
    }

    /**
     * Gets the value of the sortExpression property.
     * 
     * @return
     *     possible object is
     *     {@link Expression }
     *     
     */
    public Expression getSortExpression() {
        return sortExpression;
    }

    /**
     * Sets the value of the sortExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expression }
     *     
     */
    public void setSortExpression(Expression value) {
        this.sortExpression = value;
    }

    /**
     * Gets the value of the sortType property.
     * 
     * @return
     *     possible object is
     *     {@link SortType }
     *     
     */
    public SortType getSortType() {
        return sortType;
    }

    /**
     * Sets the value of the sortType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SortType }
     *     
     */
    public void setSortType(SortType value) {
        this.sortType = value;
    }

    /**
     * Gets the value of the sortOrder property.
     * 
     * @return
     *     possible object is
     *     {@link SortOrder }
     *     
     */
    public SortOrder getSortOrder() {
        return sortOrder;
    }

    /**
     * Sets the value of the sortOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link SortOrder }
     *     
     */
    public void setSortOrder(SortOrder value) {
        this.sortOrder = value;
    }

}
