//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:06:52 PM GMT+05:30 
//


package com.ebay.marketplace.search.v1.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SortType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SortType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="bestMatchSortType" type="{http://www.ebay.com/marketplace/search/v1/services}BestMatchSortType"/>
 *         &lt;element name="distanceSortType" type="{http://www.ebay.com/marketplace/search/v1/services}DistanceSortType"/>
 *         &lt;element name="itemSortType" type="{http://www.ebay.com/marketplace/search/v1/services}ItemSortType"/>
 *         &lt;element name="pricePlusShippingSortType" type="{http://www.ebay.com/marketplace/search/v1/services}PricePlusShippingSortType"/>
 *         &lt;element name="imageSimilaritySortTypeByItem" type="{http://www.ebay.com/marketplace/search/v1/services}ImageSimilaritySortTypeByItem"/>
 *         &lt;element name="imageSimilaritySortTypeBySignature" type="{http://www.ebay.com/marketplace/search/v1/services}ImageSimilaritySortTypeBySignature"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SortType", propOrder = {
    "bestMatchSortType",
    "distanceSortType",
    "itemSortType",
    "pricePlusShippingSortType",
    "imageSimilaritySortTypeByItem",
    "imageSimilaritySortTypeBySignature"
})
public class SortType {

    protected BestMatchSortType bestMatchSortType;
    protected DistanceSortType distanceSortType;
    protected ItemSortType itemSortType;
    protected PricePlusShippingSortType pricePlusShippingSortType;
    protected ImageSimilaritySortTypeByItem imageSimilaritySortTypeByItem;
    protected ImageSimilaritySortTypeBySignature imageSimilaritySortTypeBySignature;

    /**
     * Gets the value of the bestMatchSortType property.
     * 
     * @return
     *     possible object is
     *     {@link BestMatchSortType }
     *     
     */
    public BestMatchSortType getBestMatchSortType() {
        return bestMatchSortType;
    }

    /**
     * Sets the value of the bestMatchSortType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BestMatchSortType }
     *     
     */
    public void setBestMatchSortType(BestMatchSortType value) {
        this.bestMatchSortType = value;
    }

    /**
     * Gets the value of the distanceSortType property.
     * 
     * @return
     *     possible object is
     *     {@link DistanceSortType }
     *     
     */
    public DistanceSortType getDistanceSortType() {
        return distanceSortType;
    }

    /**
     * Sets the value of the distanceSortType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistanceSortType }
     *     
     */
    public void setDistanceSortType(DistanceSortType value) {
        this.distanceSortType = value;
    }

    /**
     * Gets the value of the itemSortType property.
     * 
     * @return
     *     possible object is
     *     {@link ItemSortType }
     *     
     */
    public ItemSortType getItemSortType() {
        return itemSortType;
    }

    /**
     * Sets the value of the itemSortType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemSortType }
     *     
     */
    public void setItemSortType(ItemSortType value) {
        this.itemSortType = value;
    }

    /**
     * Gets the value of the pricePlusShippingSortType property.
     * 
     * @return
     *     possible object is
     *     {@link PricePlusShippingSortType }
     *     
     */
    public PricePlusShippingSortType getPricePlusShippingSortType() {
        return pricePlusShippingSortType;
    }

    /**
     * Sets the value of the pricePlusShippingSortType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PricePlusShippingSortType }
     *     
     */
    public void setPricePlusShippingSortType(PricePlusShippingSortType value) {
        this.pricePlusShippingSortType = value;
    }

    /**
     * Gets the value of the imageSimilaritySortTypeByItem property.
     * 
     * @return
     *     possible object is
     *     {@link ImageSimilaritySortTypeByItem }
     *     
     */
    public ImageSimilaritySortTypeByItem getImageSimilaritySortTypeByItem() {
        return imageSimilaritySortTypeByItem;
    }

    /**
     * Sets the value of the imageSimilaritySortTypeByItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageSimilaritySortTypeByItem }
     *     
     */
    public void setImageSimilaritySortTypeByItem(ImageSimilaritySortTypeByItem value) {
        this.imageSimilaritySortTypeByItem = value;
    }

    /**
     * Gets the value of the imageSimilaritySortTypeBySignature property.
     * 
     * @return
     *     possible object is
     *     {@link ImageSimilaritySortTypeBySignature }
     *     
     */
    public ImageSimilaritySortTypeBySignature getImageSimilaritySortTypeBySignature() {
        return imageSimilaritySortTypeBySignature;
    }

    /**
     * Sets the value of the imageSimilaritySortTypeBySignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageSimilaritySortTypeBySignature }
     *     
     */
    public void setImageSimilaritySortTypeBySignature(ImageSimilaritySortTypeBySignature value) {
        this.imageSimilaritySortTypeBySignature = value;
    }

}
